### PR TITLE
Improve stability

### PR DESCRIPTION
**Pull request by billsacks**
@whlipscomb can you please double-check the changes I made here?

### CODE REVIEW

**Comment by whlipscomb** [comment]
@billsacks, These fixes look good to me.  Thanks!

When the changes are checked in, I'd like to run a 1000-year TG test out of the box as a sanity check, just to make sure we haven't missed something.

**Comment by billsacks** [comment]
@whlipscomb I can't reproduce the error you ran into with manage_externals: I tried pointing source_cism to a hash that had not yet been fetched in the current directory, then reran checkout_externals and (as it should) it fetched from the remote and then successfully checked out the hash. But I'm concerned about this. Please let me know if you run into this again, and if so, I'd like to work harder to try to reproduce it.

**Comment by whlipscomb** [comment]
@billsacks , I just did a fresh clone of cism-wrapper, checked out improve_stability, and had no problem with the manage_externals step.  I can't explain what happened the first time, but hopefully it won't recur.

I'm running a TG1850G case now.  So far so good after 100 years.

**Comment by whlipscomb** [comment]
@billsacks and @gunterl, I launched a 5 ka TG run on cheyenne using the improve_stability branch.  As of now we're 3500 years in, with no signs of instability in the troublesome Kangerlussuaq or Jakobshavn regions.  I ran through the output fields and everything looked good, including the snapshots of acab_applied, bmlt_applied and calving_rate.  So I think we're good to go with our CISM release code and default config parameters.

**Comment by billsacks** [comment]
Fantastic, thanks for letting us know!

**Comment by gunterl** [comment]
This is great!

**Pull request merged**
